sudo: true
language: node_js
node_js:
- lts/*
- '6'
services:
- docker
before_install:
- docker pull docker.elastic.co/elasticsearch/elasticsearch:6.5.3
- sudo sysctl -w vm.max_map_count=262144
- docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.5.3
- sleep 10
script:
- npm run report
after_script:
- npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
- mkdir ./deploy && cp ./README.md ./deploy
deploy:
  provider: s3
  access_key_id:
    secure: bjznPxYScuUHbQ22r+bHgX3lnp6gSbVw7B59h8lik8rxWyEymDdAclBqtTQO/v8Gn17tNFCFIYp70tCGDeZ1gxxO5EfUdfhc9W0p6aHYEzl2wP24A7uEY/kvBAgmhLFvbr0OW3OTCDNCj7rnbJLnCtoNolSDmf5W/iMSm7UkWxsICrxERcmApEabESm+kVBBFbwOshH4LPL/I8Md7iR5L1hDOV7bF00/eQRkZiZ27wmwoYGM0lyqHezi73zQ4Bj9BjB7cqcawnw0SI4NBdKOsXN9Wk3CMWYTyjhtUn/HOl8/AAgc+C2M3lU7Upp+QXT54jbiUorhRkbb1gu6IlW/LZLcUoCiUECZniUSoIxAAtNZIZ13dW/fNQV6fFYikbGLHDBe88csHdszTjehAcr/Ej23JhAVjHV0ogRBViiUUTsqSwqNe+TARfxTL3ybZSr04FMnt4JREjh5G/dbH+HKDxRsbeUccLMTZcGGNbiMeUrXzXregFqMOei6U0CP6ryNntOrKGub5LdEZK14FInucV7PfgO9FMHxVSalgBe/wWVaq6rpET18S64YdvD5/37oA23ST68kjhe7xwgahQGhk6L7b1g4D96NWDUrkqSWHF3NGPIt7jbW8X3jGEdhikjK+lMennrssTGFByMVMeH+lA37gTI1CvESXsL1DWb51O0=
  secret_access_key:
    secure: CJoqiMd7wf9kvLu2VXhxjgYIeFBqqLGLjEC/DIhW4URGzT/GCzPty7lD4/jHPn16Ikqm2HkSvKA3dqCiyjLHSSz1sTKiglywXmwaUcvE6/4KwUwRjVNVuz6011haNd0yyGb2FA5U0SHCN3xmStzPR3dE9l1G5NkEoHEPBIFbZA1vWcZbvPR3Yl6Wxk4mvZI51bTBexXG+4V9GEEvSjWEnpUAGVDb+P3QKghgLnmuyeMbVzciE2LVz1qMp5wP9h0JaaPqykc+55HMA5FyUI13qjrL0RZG0viQq4AB+6+bLPWB5pzLHtMa6H0iw7AghMf7RDEXQTqX4I5I1A84th+zAeA9E0uP8jVBcYWtRWM94uAx+o6hstaEnQWMMUHVrl1JKMsdnu1KAWtGSXtOh/AAc8P4DUWR3Woq0E1yfRFi2OyA/tQ5c3SM3QuLCJNF9cw2Jkio7gMgx/lXCnhOaxcT+H3osxLC0nOfAANVUpEI4SWE1/GDqSh9QVP69v2A11wuMwqzRKvU0zFB+TnUKLaoVzGqUm04C+ONZryPLbi26y/Cdt53XVxiwaTn2tdDzxE/NBFou/Ve5IhAiqg9GEf6hiyAFiCpiWLsem9g4GtwWA3jiNQqeIO18PFOGLFsNLfLhFJXgglhzr1bwMm+Vi+ola4Hjm2n/oSviMOON2ttgKI=
  bucket: okanjo-docs
  skip_cleanup: true
  upload-dir: okanjo-app-elastic
  acl: public_read
  detect_encoding: true
  default_text_charset: utf-8
  local_dir: deploy
  on:
    branch: master
    repo: Okanjo/okanjo-app-elastic
